export const NON_APPROVED = 'NON_APPROVED';
export const PLANIFICATION = 'PLANIFICATION';
export const APPROVED = 'APPROVED';
export const BIDDING_OPEN = 'BIDDING_OPEN';
export const BIDDING_CLOSED = 'BIDDING_CLOSED';

export const PERIOD_OPEN = 'PERIOD_OPEN';
export const PERIOD_CLOSED = 'PERIOD_CLOSED';
export const INTERPRET_PERIOD = 'INTERPRET_PERIOD';
export const APPROVE_PERIOD = 'APPROVE_PERIOD';
export const TRANSFER_PERIOD = 'TRANSFER_PERIOD';

